/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AfcAlert: typeof import('./components/notifications/AfcAlert.vue')['default']
    BedMeshToolPanel: typeof import('./components/panels/BedMeshToolPanel.vue')['default']
    ColorPickerDialog: typeof import('./components/dialogs/ColorPickerDialog.vue')['default']
    ConfigEditorPanel: typeof import('./components/panels/ConfigEditorPanel.vue')['default']
    ControlPanel: typeof import('./components/panels/ControlPanel.vue')['default']
    CurrentPrintPanel: typeof import('./components/panels/CurrentPrintPanel.vue')['default']
    ExtruderPanel: typeof import('./components/panels/ExtruderPanel.vue')['default']
    FanDialog: typeof import('./components/dialogs/FanDialog.vue')['default']
    KeyboardOverlay: typeof import('./components/KeyboardOverlay.vue')['default']
    KlipperAlert: typeof import('./components/notifications/KlipperAlert.vue')['default']
    LaneDialogAFC: typeof import('./components/afc/LaneDialogAFC.vue')['default']
    MoonrakerAlert: typeof import('./components/notifications/MoonrakerAlert.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    NetworkPanel: typeof import('./components/panels/NetworkPanel.vue')['default']
    NotificationPanel: typeof import('./components/panels/NotificationPanel.vue')['default']
    PanelAFC: typeof import('./components/afc/PanelAFC.vue')['default']
    PidToolPanel: typeof import('./components/panels/PidToolPanel.vue')['default']
    PowerDialog: typeof import('./components/dialogs/PowerDialog.vue')['default']
    PrintDialog: typeof import('./components/dialogs/PrintDialog.vue')['default']
    PrintFilePanel: typeof import('./components/panels/PrintFilePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortcutBar: typeof import('./components/ShortcutBar.vue')['default']
    ShortcutBarAFC: typeof import('./components/afc/ShortcutBarAFC.vue')['default']
    ShortcutBarButton: typeof import('./components/ShortcutBarButton.vue')['default']
    ShortcutBarControls: typeof import('./components/ShortcutBarControls.vue')['default']
    ShortcutBarShortcutButton: typeof import('./components/ShortcutBarShortcutButton.vue')['default']
    ShortcutButtonEditDialog: typeof import('./components/dialogs/ShortcutButtonEditDialog.vue')['default']
    ShortcutButtonsPanel: typeof import('./components/panels/ShortcutButtonsPanel.vue')['default']
    SkipObjectDialog: typeof import('./components/dialogs/SkipObjectDialog.vue')['default']
    SpeedDialog: typeof import('./components/dialogs/SpeedDialog.vue')['default']
    TempDialog: typeof import('./components/dialogs/TempDialog.vue')['default']
    ToolsPanel: typeof import('./components/panels/ToolsPanel.vue')['default']
    TunePanel: typeof import('./components/panels/TunePanel.vue')['default']
    WebcamToolPanel: typeof import('./components/panels/WebcamToolPanel.vue')['default']
    WifiNetworkDialog: typeof import('./components/dialogs/WifiNetworkDialog.vue')['default']
    WifiSavedDialog: typeof import('./components/dialogs/WifiSavedDialog.vue')['default']
    WifiScanDialog: typeof import('./components/dialogs/WifiScanDialog.vue')['default']
  }
}
