/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExtruderPanel: typeof import('./components/panels/ExtruderPanel.vue')['default']
    FanDialog: typeof import('./components/dialogs/FanDialog.vue')['default']
    LaneDialogAFC: typeof import('./components/afc/LaneDialogAFC.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    PanelAFC: typeof import('./components/afc/PanelAFC.vue')['default']
    PanelExtruder: typeof import('./components/panels/PanelExtruder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortcutBar: typeof import('./components/ShortcutBar.vue')['default']
    ShortcutBarAFC: typeof import('./components/afc/ShortcutBarAFC.vue')['default']
    ShortcutBarButton: typeof import('./components/ShortcutBarButton.vue')['default']
    ShortcutBarControls: typeof import('./components/ShortcutBarControls.vue')['default']
    ShortcutBarExtruder: typeof import('./components/ShortcutBarExtruder.vue')['default']
    TempDialog: typeof import('./components/dialogs/TempDialog.vue')['default']
  }
}
